name: ruamlek
description: แอปรวมเลข (ทดสอบ) - บันทึกเลข 2/3 หลัก + รวมยอด
publish_to: "none"
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
